---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{DEPLOYMENT_NAME}}-deployment
  namespace: {{NAMESPACE}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{DEPLOYMENT_NAME}}-app
  template:
    metadata:
      labels:
        app: {{DEPLOYMENT_NAME}}-app
    spec:
      containers:
      - name: {{DEPLOYMENT_NAME}}-app-container
        image: {{IMAGE}}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: registry-secret